# Server configuration
server:
  context-path: /micro
  port: 8080

# Spring properties
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://cap-sg-prd-4.securegateway.appdomain.cloud:19605/inventorydb
    username: root
    password: root
  jpa:
    database: MYSQL